const types = {
  LOADING: "LOADING",
  AUTHENTICATE_REQUEST: "AUTHENTICATE_REQUEST",
  AUTHENTICATE_SUCCESS: "AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAILURE: "AUTHENTICATE_FAILURE",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  CHANGE_PROFILE_IMAGE: "CHANGE_PROFILE_IMAGE",
  STOP_LOADING: "STOP_LOADING"
}

export default types;
